// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLHfy2PYIFcRZB9zoUZzrf-LmSaa9b90',
    appId: '1:726871891657:web:0f58e58f488093ed1bf718',
    messagingSenderId: '726871891657',
    projectId: 'tuboslab1',
    authDomain: 'tuboslab1.firebaseapp.com',
    storageBucket: 'tuboslab1.firebasestorage.app',
    measurementId: 'G-YDCJWX1MMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZP4E365fybYHVditPCI-X5EyDUnkyDN0',
    appId: '1:726871891657:android:6343ee27effa90521bf718',
    messagingSenderId: '726871891657',
    projectId: 'tuboslab1',
    storageBucket: 'tuboslab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLi4BJ_70muY7o6mtMPOxeYboSYzkXv1I',
    appId: '1:726871891657:ios:1db32725532e93871bf718',
    messagingSenderId: '726871891657',
    projectId: 'tuboslab1',
    storageBucket: 'tuboslab1.firebasestorage.app',
    iosBundleId: 'com.example.tubosApp',
  );
}
